[controller][dvc][venice-common][test] Add Pub Sub Admin Interface.
linkedin/venice pull request #266
Opened 2023-03-07 18:53 UTC by haoxu07

## Summary, imperative, start upper case, don't end with a period

This change focus on these things:
1. Changing the interface of original `KafkaAdminWrapper` with Kafka assumption to our internal Pub Sub interfaces. Previously, `KafkaAdminWrapper` only have 2 subclasses:  `KafkaAdminClient` and `InstrumentedKafkaAdminClient`. 
2. Remove the previous Raw Bytes Kafka Consumer and Kafka Record Consumer creating method from `KafkaClientFactory`, as these 2 types of consumers are mainly used by `PartitionOffsetFetcherImpl` from `TopicManager` for admin purpose.  Instead, a Kafka record consumer is created inside the `KafkaAdminClient` to do the job of polling few records and offset fetching purpose. 
3. Changes on other components to adapt the `TopicManger` interface change with `PubSubTopic` assumption.
4. Some test cleanups by adding `Utils.getUniqueTopicString` to simplify the `PubSubTopic` creation in the unit test. 

Suggested review order:
1. KafkaAdminWrapper (I will change it into `PubSubAdmin` or `PubSubAdminAdaptor`.) and its subclasses of KafkaAdminClient.
3. `PartitonOffsetFetcherImpl` and `TopicManager`
6. `TopicCleanupService`, `VeniceHelixAdmin`, and `StoreIngestionTask` e.g. change for `TopicManager`  

## How was this PR tested?

Internal CI
## Does this PR introduce any user-facing changes?

- [*] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

2023-03-14 18:29 UTC, sushantmane requested changes
Thanks, @haoxu07. I've left some comments please take a look.

IMO points that we should address:
1. Not mixing up admin and consumer methods
2. Keeping changes consistent with the producer adapter, for example, move all Kafka admin-related configs to a separate file. We can find a better way if the producer adapted style is not good enough.

2023-03-14 18:29 UTC, sushantmane commented on internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/writer/VeniceWriterTest.java
> +      // List<TopicPartition> partitions = Collections.singletonList(new TopicPartition(topicName, 0));
maybe delete the commented code?

2023-03-14 18:29 UTC, sushantmane commented on services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
> +          new VeniceWriterOptions.Builder(pushJobDetailsRTTopic.getName())
I think we should just update builder to use `PubSubTopic` object instead of topic name string

2023-03-14 18:29 UTC, sushantmane commented on services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
> +      PubSubTopic versionTopic = pubSubTopicRepository.getTopic(Version.composeKafkaTopic(storeName, versionNumber));
We should also consider adding `PubSubTopicRepository::getVtTopic(String storeName, int version)`

2023-03-14 18:29 UTC, sushantmane commented on services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
> +        new PubSubTopicRepository());
Why is this not injected from `VeniceController`?

2023-03-14 18:29 UTC, sushantmane commented on services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/TopicCleanupService.java
> -              "Received exception while trying to clean up replica statuses from meta system store for topic: {}, but topic deletion will continue",
Using interpolation `{}` for exception will prevent stack trace from being logged. 

If we want stack trace then the exception should be the last parameter (without corresponding `{}`) in the log statement.

2023-03-14 18:29 UTC, sushantmane commented on services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupService.java
> +    // storeTopics1.put(getPubSubTopic("non_venice_topic1", ""), Long.MAX_VALUE);
remove dead code

2023-03-14 18:29 UTC, sushantmane commented on services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupService.java
> +    // verify(topicManager, never()).ensureTopicIsDeletedAndBlockWithRetry(getPubSubTopic("non_venice_topic1", ""));
remove dead code

2023-03-14 18:29 UTC, sushantmane commented on services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupServiceForMultiKafkaClusters.java
> +    // storeTopics.put("non_venice_topic1", 1000l);
delete

2023-03-14 18:29 UTC, sushantmane commented on internal/venice-common/src/main/java/com/linkedin/venice/kafka/KafkaClientFactory.java
> +  public KafkaAdminWrapper getReadOnlyKafkaAdmin(
I don't think we really need different variations(read-only and write-only) of Admin API. I know they have been there in the code already, but IIUC they are not necessary anymore. Can we just keep once of them?

2023-04-24 17:53 UTC, closed without merging

2023-04-24 17:54 UTC, haoxu07 commented
This PR has been included in the merged one: https://github.com/linkedin/venice/pull/279