[client] Allow to configure the number of connections and upgrade HttpClient to 5.x async with HTTP2 support
linkedin/venice pull request #453
Opened 2023-05-29 12:18 UTC by eolivelli

## Summary

The Store Client currently has some limitations about performances: it uses only HTTP 1.1 and opens only at most 2 connections. This means that you cannot have more than 2 inflight requests.

Un order to achieve better latencies this patch introduces:
- configuration parameters to tune the number. of HTTP 1.x connections
- upgrade of HttpClient to 5.x, with HTTP2 support
- a configuration flag to require HTTP2

Please note that HTTP2 works only with TLS enabled on the Router  

## How was this PR tested?
The code change is almost covered by existing tests, as the core of the change is the upgrade of HC to 5.x.

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

Currently there is no documentation about the client

2023-05-29 15:08 UTC, FelixGV reviewed
Thanks for the PR Enrico!

This looks fine in theory but I wonder if there's a risk. We've occasionally seen some instabilities with httpclient5, and I wonder if we should keep the support for the previous version. Since the `TransportClient` is pluggable, and the package names are different, it seems feasible to support both.

This doesn't really affect us within LI since we use the `D2TransportClient` anyway, so I'm not sure what's the likelihood that HC5 could have a regression compared to 4.

@gaojieliu do you have an opinion on the above?

2023-05-30 21:21 UTC, gaojieliu commented
> Thanks for the PR Enrico!
> 
> This looks fine in theory but I wonder if there's a risk. We've occasionally seen some instabilities with httpclient5, and I wonder if we should keep the support for the previous version. Since the `TransportClient` is pluggable, and the package names are different, it seems feasible to support both.
> 
> This doesn't really affect us within LI since we use the `D2TransportClient` anyway, so I'm not sure what's the likelihood that HC5 could have a regression compared to 4.
> 
> @gaojieliu do you have an opinion on the above?

Yeah, what you said makes sense.
Let us keep both httpsyncclient (for http/1.1) and httpclient5 for (http2) for the time being, since we did discover a couple issues with httpclient5 in the past.
Once the new httpclient5 based implementation is stablized, we could delete the httpasyncclient based imp.

2023-05-30 21:55 UTC, gaojieliu requested changes

2023-05-30 21:55 UTC, gaojieliu commented on clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientConfig.java
> +
So Venice Thin Client doesn't AsyncHttpClient any more, right?
I guess you can remove `AsyncHttpClient` from the javadoc.

2023-05-30 21:55 UTC, gaojieliu commented on clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientConfig.java
> +  private boolean requireHTTP2;
Can this config to be more specific? such as `httpClient5Http2Enabled`? since D2 based impl doesn't read this config.

2023-05-30 21:55 UTC, gaojieliu commented on clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/transport/HttpsTransportClient.java
> +      return HttpAsyncClients.customHttp2()
Can we leverage this utility class to instantiate a httpclient5 based h2 client?
https://github.com/linkedin/venice/blob/main/internal/venice-client-common/src/main/java/com/linkedin/venice/httpclient5/HttpClient5Utils.java

The utility class has been proved inside LinkedIn.

2023-06-08 07:14 UTC, eolivelli commented
@gaojieliu @FelixGV I have rebased onto the latest main branch.

After the discussion we had yesterday at the community meeting I believe that patch is good to go.
We said that at LI nobody is currently using this Transport and it is fine to upgrade HC5 to fine.

DataStax will provide feedback on the stability of this client, as we are going to use this for our testing and for our users

2023-06-08 15:18 UTC, FelixGV approved these changes

2023-06-08 15:18 UTC, FelixGV commented on clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/transport/HttpTransportClient.java
> +  private final static Logger LOGGER = LogManager.getLogger(HttpTransportClient.class);
Thanks, that's better.

2023-06-08 17:07 UTC, gaojieliu approved these changes

2023-06-08 17:07 UTC, merged