Make tags
linkedin/venice pull request #47
Opened 2022-10-12 19:50 UTC by majisourav99

To push and release tags on github we need committer info. This PR adds support to pass github token to make API calls to github for adding tags.

2022-10-12 19:55 UTC, nisargthakkar reviewed
Please edit PR title to be more descriptive and add a `[build]` tag

2022-10-12 19:55 UTC, nisargthakkar commented on make_tag.py
> +@click.option('--github-token', default = ' ', help='The github token used for API call')
Let's make the default as `None`?

2022-10-12 19:55 UTC, nisargthakkar commented on make_tag.py
> +        os.system('./curltag.sh {} {}' .format(str(tag_name), str(github_token)))
Let's use `requests` to make the API calls instead of curl and shell script

2022-10-12 19:55 UTC, nisargthakkar commented on curltag.sh
> +    EOF
Can you add some test section to the PR description?

2022-10-12 20:01 UTC, nisargthakkar requested changes

2022-10-12 20:01 UTC, nisargthakkar commented on .github/workflows/build-and-upload-archives-on-schedule.yml
>  jobs:
If the deploy keys work, we'll need to pass them via env vars. Check this for an example in another action: https://github.com/linkedin/venice/blob/main/.github/workflows/build-and-upload-archives-upon-creating-tags.yml#L38

2022-10-13 01:06 UTC, nisargthakkar commented on make_tag.py
> +        response = requests.post('https://api.github.com/repos/linkedin/venice/git/refs', headers=headers, json={"ref": "refs/tags/" + tag_name, "sha" : "$commit"})
`$commit` needs to be an actual commit reference

two nits:
1. Let's use `''` where possible (to follow the pattern of the rest of the file)
2. we can use `fstring` for `tag_name` now: `f'refs/tags/{tag_name}'`

2022-10-13 01:06 UTC, nisargthakkar commented on make_tag.py
> +            print("Could not push the tag " + tag_name)
Let's change `push` to `create`
Also, same nit - use `''`

2022-10-13 21:06 UTC, nisargthakkar requested changes

2022-10-13 21:06 UTC, nisargthakkar commented on make_tag.py
> +@click.option('--github-token',  help='The github token used for API call')
nit: extra whitespace before `help`

2022-10-13 21:06 UTC, nisargthakkar commented on make_tag.py
> +        commit = call(['git', 'rev-parse', 'HEAD'])
The return value of `call` is the command's exit status

2022-10-13 21:18 UTC, majisourav99 commented on make_tag.py
> +            'Content-Type': 'application/x-www-form-urlencoded',
you mean the header?

2022-10-13 21:24 UTC, nisargthakkar commented on make_tag.py
> +            'Content-Type': 'application/x-www-form-urlencoded',
The `Content-Type` specifically

2022-10-13 21:28 UTC, majisourav99 commented on make_tag.py
> +            'Content-Type': 'application/x-www-form-urlencoded',
some SO article I saw used application/json. But guess it not necessary

2022-10-13 22:01 UTC, nisargthakkar commented on make_tag.py
> +            'Content-Type': 'application/x-www-form-urlencoded',
If we use `json=...` in `requests`, then the library adds the header automatically

2022-10-13 22:04 UTC, nisargthakkar commented on curltag.sh
> +    EOF
@majisourav99 Can you add this?

2022-10-14 05:23 UTC, nisargthakkar approved these changes
LGTM

2022-10-14 16:21 UTC, merged