[router] Cleanup per storage node router quota code
linkedin/venice pull request #548
Opened 2023-07-25 23:14 UTC by majisourav99

## [router] Cleanup per storage node router quota code

Since per store router quota is deployed in all fabrics, this PR cleans up per storage node quota code and associated tests.
## How was this PR tested?

GHCI
## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

2023-07-26 17:11 UTC, gaojieliu requested changes

2023-07-26 17:56 UTC, majisourav99 commented on services/venice-router/src/main/java/com/linkedin/venice/router/throttle/ReadRequestThrottler.java
> +      long storageNodeQuotaCheckTimeWindow) {
you mean `perStorageNodeReadQuotaBuffer` ? I can remove it

2023-07-26 17:56 UTC, majisourav99 commented on services/venice-router/src/main/java/com/linkedin/venice/router/throttle/ReadRequestThrottler.java
>    public void onExternalViewChange(PartitionAssignment partitionAssignment) {
Sure

2023-07-26 18:32 UTC, gaojieliu commented on services/venice-router/src/main/java/com/linkedin/venice/router/throttle/ReadRequestThrottler.java
> +      long storageNodeQuotaCheckTimeWindow) {
Also `storageNodeQuotaCheckTimeWindow`.

2023-07-27 17:27 UTC, gaojieliu commented on services/venice-router/src/main/java/com/linkedin/venice/router/throttle/ReadRequestThrottler.java
> -        routerConfig.getPerStorageNodeReadQuotaBuffer(),
Can we get rid of this config: `getPerStorageNodeReadQuotaBuffer` from VeniceRouterConfig as well? Also the corresponding config entries in `ConfigKeys`?

2023-07-27 18:39 UTC, gaojieliu approved these changes

2023-07-27 19:27 UTC, merged