Add bootstrap change capture consumer
linkedin/venice pull request #685
Opened 2023-10-06 21:07 UTC by zx0401

## Summary, imperative, start upper case, don't end with a period

Resolves #XXX

## How was this PR tested?

## Does this PR introduce any user-facing changes?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

2023-10-12 16:53 UTC, haoxu07 requested changes

2023-10-13 06:33 UTC, zx0401 commented on clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/BootstrappingVeniceChangelogConsumer.java
> + * enables more fine control.  This interface is intentionally limited as implementors rely on local checkpointing and
Updated

2023-10-13 06:33 UTC, zx0401 commented on clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
> +  private static final String LOCAL_STATE_TOPIC_NAME = "ChangeCaptureBootstrap_v1";
That's a good point. Updated.

2023-10-25 20:20 UTC, ZacAttack approved these changes
Looks great!  Thanks for the hardwork!

2023-10-25 20:44 UTC, merged