[server][da-vinci] reduced DIV warn logging frequency to reduce cpu wait especially during rewind
linkedin/venice pull request #726
Opened 2023-10-31 23:56 UTC by gaojieliu

## Summary, imperative, start upper case, don't end with a period
reduced DIV warn logging frequency to reduce cpu wait especially during rewind

## How was this PR tested?
CI

## Does this PR introduce any user-facing changes?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

2023-10-31 23:59 UTC, sixpluszero commented on clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
> +        String errorMsgIdentifier = consumerRecord.getTopicPartition().getPubSubTopic().getName() + "-"
but warnMessage should contain details of producer right? Should we ignore that?

2023-11-01 00:00 UTC, sixpluszero commented on clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
> +        String errorMsgIdentifier = consumerRecord.getTopicPartition().getPubSubTopic().getName() + "-"
NVM. Didn't see the getClass().getName() this should be OK.

2023-11-01 00:30 UTC, FelixGV requested changes
I would prefer that we do something a bit different...

Specifically for the case of the non-SOS first message, completely suppress the log (and probably stop incrementing the missing metric as well, as it is misleading...), basically, treat it as a fully ok write (assuming EOP is already gotten of course).

For all other missing data, log it everytime. No redudant filter anywhere...

2024-02-29 22:01 UTC, gaojieliu commented
This PR needs some re-work and I will take another look soon.

2024-03-14 17:34 UTC, majisourav99 approved these changes

2024-04-02 16:18 UTC, gaojieliu commented
@lluwm has already merged a fix:
https://github.com/linkedin/venice/pull/905
I will discard this one.

2024-04-02 16:18 UTC, closed without merging